# docker-compose.yml

services:
  pgdatabase:
    image: postgres:16
    container_name: postgres_container
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadminpw
      - POSTGRES_DB=sqldatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Maps host port 5433 to container port 5432
    networks:
      - data-engineering

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
    networks:
      - data-engineering
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  etl:
    build: .
    env_file: .env
    depends_on:
      - pgdatabase
    volumes:
      - ./datasets:/data/datasets
      - ./logs:/logs
      - ./spark-temp:/tmp/spark-temp 
    environment:
      - PYSPARK_PYTHON=python3
    command: ["python", "etl.py"]
    networks:
      - data-engineering

volumes:
  pgdata: # Named volume for PostgreSQL data persistence
  pgadmin_data: # Named volume for pgAdmin data persistence

networks:
  data-engineering: # Custom network for inter-service communication